name: Build
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build:
    name: Build
    runs-on: quay.io/centos/centos:stream8
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Build image
        run: docker-compose build
      - name: Run plugin
        run: docker-compose up